[package]
name = "rs-sol"
version = "0.1.1"
edition = "2024"
authors = ["Esat Mustafa Namli"]

[dependencies]


[[bin]]
name = "lc_sols-rs"
path = "src/main.rs"


[build-dependencies]
regex = { version = "1.11" }

[dev-dependencies]
proptest = "1.7.0"
