build_with_asm_release:
    RUSTFLAGS="--emit=asm" cargo build --release

build_with_asm_release_valgrind:
    RUSTFLAGS="--emit=asm" cargo build --release && valgrind ./target/release/lc_sols-rs

build_and_run_valgrind:
    cargo build --release && valgrind ./target/release/lc_sols-rs

test_all:
    cargo test

test_all_with_valgrind:
    cargo test --no-run --message-format=json | jq -r "select(.profile.test == true) | .filenames[]" | xargs -n1 valgrind --leak-check=full

run_backtrace:
    RUST_BACKTRACE=1 cargo run